# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Building pthmgr.
        run: msbuild.exe pthmgr.sln -Configuration Release

      - name: Building Python Extension (x64).
        run: python setup.py build

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x86'
      - name: Building Python Extension (x86).
        run: python setup.py build
