# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_python:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.0', '3.1', '3.2', '3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        architecture: [x86, x64]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Building Python Extension (${{ matrix.architecture }}).
        run: python setup.py build

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]
        build-platform: [Win32, x64]
        exclude:
          - architecture: x86
            build-platform: x64
          - architecture: x64
            build-platform: Win32

    steps:
      - uses: actions/checkout@v2
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Install vcultimate2010
        run: choco install vcultimate2010full --source="./"

      - name:  Setup Environment
        run:   |
             echo "{C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE}" >> $GITHUB_PATH
             echo "{C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN}" >> $GITHUB_PATH
             echo "{C:\Windows\Microsoft.NET\Framework\v4.0.30319}" >> $GITHUB_PATH
             echo "{LIB}={C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;%LIB%}" >> $LIB
             echo "{LIB}={C:\Program Files (x86)\Microsoft SDKs\Windows\v6.0A\Lib;%LIB%}" >> $LIB
             echo "{LIB}={C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Lib;%LIB%}" >> $LIB
             echo "{INCLUDE}={C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include;%INCLUDE%}" >> $INCLUDE

      - name:  Start VCTools
        run: call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" ${{ matrix.architecture }}
        shell: cmd

      - name: Building pthmgr (${{ matrix.architecture }}).
        run: msbuild.exe pthmgr.sln -p:Configuration=Release -p:Platform=${{ matrix.build-platform }}
