# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Building Python Extension (x64).
        run: python setup.py build

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x86'

      - name: Building Python Extension (x86).
        run: python setup.py build

      - name: Install vcexpress2010
        run: choco install vcexpress2010

      - name:  Setup Environment
        run:   |
             echo "{C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE}" >> $GITHUB_PATH
             echo "{C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN}" >> $GITHUB_PATH
             echo "{C:\Windows\Microsoft.NET\Framework\v4.0.30319}" >> $GITHUB_PATH
             echo "{LIB}={C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;%LIB%}" >> $LIB
             echo "{LIB}={C:\Program Files (x86)\Microsoft SDKs\Windows\v6.0A\Lib;%LIB%}" >> $LIB
             echo "{LIB}={C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Lib;%LIB%}" >> $LIB
             echo "{INCLUDE}={C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include;%INCLUDE%}" >> $INCLUDE

      - name:  Start VCTools
        run: call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
        shell: cmd

      - name: Building pthmgr.
        run: msbuild.exe pthmgr.sln -p:Configuration=Release
